# config/ros2_controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # 关节状态广播器 - 这是关键!
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 左臂控制器
    l_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # 右臂控制器
    r_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


# 关节状态广播器配置
joint_state_broadcaster:
  ros__parameters:
    joints:
      - L_R01_Joint
      - L_R02_Joint
      - L_R03_Joint
      - L_R04_Joint
      - L_R05_Joint
      - L_R06_Joint
      - R_R01_Joint
      - R_R02_Joint
      - R_R03_Joint
      - R_R04_Joint
      - R_R05_Joint
      - R_R06_Joint
    interfaces:
      - position
      - velocity


# 左臂控制器配置
l_arm_controller:
  ros__parameters:
    joints:
      - L_R01_Joint
      - L_R02_Joint
      - L_R03_Joint
      - L_R04_Joint
      - L_R05_Joint
      - L_R06_Joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    action_monitor_rate: 20.0
    
    state_publish_rate: 50.0
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0


# 右臂控制器配置
r_arm_controller:
  ros__parameters:
    joints:
      - R_R01_Joint
      - R_R02_Joint
      - R_R03_Joint
      - R_R04_Joint
      - R_R05_Joint
      - R_R06_Joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    action_monitor_rate: 20.0
    
    state_publish_rate: 50.0
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0